# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160918_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
