# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20161007_2238'),
        ('kfet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
