# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160721_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
