# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-17 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160721_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_conscrit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
