# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-17 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160917_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='radreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=17)),
                ('attribute', models.CharField(default='WISPR-Bandwidth-Max-Down', max_length=254)),
                ('op', models.CharField(default='=', max_length=2)),
                ('value', models.CharField(default='960000', max_length=254)),
            ],
            options={
                'db_table': 'radreply',
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
